version: 2.1
executors:

  release:
    docker:
      - image: circleci/node:10.16.1
  terraform:
    docker:
      - image: hashicorp/terraform:0.13.0

jobs:
  validate:
    executor: terraform
    steps:
      - checkout
      - run:
          name: Terraform Validate
          command: |
            terraform init
            terraform validate
          no_output_timeout: 30m

  plan:
    executor: terraform
    steps:
      - checkout
      - run:
          name: Terraform Plan
          command: |
            terraform init
            terraform plan
          no_output_timeout: 30m

  release:
    executor: release
    steps:
      - checkout
      - run:
          name: Release-it
          command: |
            npm install
            git config --global user.email "wesley@stratotechnology.com"
            git config --global user.name "Wesley Charles Blake"
            npm run release --ci


workflows:
  version: 2
  build-and-deploy:
    jobs:

      - validate
      - plan:
          requires:
            - validate
      - release:
          context: CI
          requires:
            - plan
          filters:
            branches:
              only: master
